openapi: 3.0.3
info:
  title: Dedicated Network - Accesses
  description: |

    This API allows for requesting access to a dedicated network for devices. A device is identified by the CAMARA _device object_, containing either an MSIDSN or a Network Access Identifier. For more information about the Dedicated Networks APIs, see the _GeneralDescription_ document in the Dedicated Networks [repository](https://github.com/camaraproject/DedicatedNetworks/).

    An Access to a dedicated network represents the permission for its devices to use the Dedicated Network's reserved connectivity resources. The usage of the resources can be tailored by the access within the constraints of the applicable Network Profile.

    A device is identified by the CAMARA `device` object, where at least one identifier for the device (user equipment) out of four options: IPv4 address, IPv6 address, Phone number, or Network Access Identifier assigned by the mobile network operator for the device.

    Notes:
    1. Support for using an IP address as device identifier is not recommended when the IP address may change. The API invoker may not be able to associate the accesses resource with the targeted device anymore.<br>Further, the device may be offline at time of Accesses API usage, thus, no IP address assigned.
    1. Network Access Identifier is defined for future use and will not be supported with this version of the API.

    <!-- CAMARA:MANDATORY:authorization-and-authentication:BEGIN -->

    # Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details of how an API consumer requests an access token. Please refer to Identity and Consent Management (https://github.com/camaraproject/IdentityAndConsentManagement/) for the released version of the profile.

    The specific authorization flows to be used will be agreed upon during the onboarding process, happening between the API consumer and the API provider, taking into account the declared purpose for accessing the API, whilst also being subject to the prevailing legal framework dictated by local legislation.

    In cases where personal data is processed by the API and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of three-legged access tokens is mandatory. This ensures that the API remains in compliance with privacy regulations, upholding the principles of transparency and user-centric privacy-by-design.
    <!-- CAMARA:MANDATORY:authorization-and-authentication:END -->

    # Identifying the device from the access token

    This API requires the API consumer to identify a device as the subject of the API as follows:
    - Since this API can handle multiple devices in one request it is strongly recommended to use a two-legged access token
    - When the API is invoked using a two-legged access token, each device will be identified by the respective `device` identifier, which therefore MUST be provided.

    ## Error handling:

    - If the subject can be identified from the access token and there is no matching `device` object, then the server will return an error with the `422 MISSING_IDENTIFIER` error code.
    - If the number of devices with access to the network is equal to or exceeds the 'maxNumberOfDevices', the API provider will provide a `429 QUOTA_EXCEEDED` error code.

    # Creating a network access for devices

    An Access for devices is created by performing a `POST` operation on the `/accesses` endpoint.

    The API Consumer provides the following information

    - the networkId to which access is being given

    - optionally, a list of identifiers of the devices, using a device object as device identifier

    - optionally, a default QoS Profile can be set for the access and all of its devices (see Network Profiles section in the dedicated-network-profiles API in the [Dedicated Networks repository](https://github.com/camaraproject/DedicatedNetworks/)).

    - optionally, a subset of QoS Profiles from this network can be provided to further restrict which QoS Profiles the devices can access

    - Optionally, callback related information through sink and sinkCredential parameters to receive notifications about the lifecycle events of the devices of the access.

    The API returns an accessId. The accessId is a unique identifier of the access, which remains unchanged during its lifetime. The accessId is needed to query the status of the Access (GET /accesses/{accessId}) and to delete Access (DELETE accesses/{accessId}).

    If a list of devices is provided in the create request, the API also returns a `recentAccessDevices` with information for each device that was recognized and could be included in the access. For performance reasons the `recentAccessDevices` is limited to 100 most recently handled devices.

    Initially, each device included in the access is in `REQUESTED` state. The device can access the network only when it is in `GRANTED` state.

    If callback related information is provided, it will be used to notify of state transitions for all devices included in the access.

     ## Error handling:

     - If the dedicated network identified by the networkId is in an incompatible state when creating a network access, e.g. it is in the TERMINATED state, then the server will return an error with the `409 INCOMPATIBLE_STATE` error code.

    # Adding devices to an access

    When an access already exists, additional devices can be added by performing a `POST` operation on the `/accesses/{accessId}/devices` collection endpoint.

    The API Consumer provides the following information

    - a list of identifiers of the devices to be added, using a device object as device identifier

    If all the requested devices could be added, the API returns a list with information for each requested device.

    If not all requested devices could be added, the API returns a result detailing which devices were added and which failed.

    If callback related information was provided for the access, it will be used to also notify of state transitions for all the newly included devices.

    # Removing devices from an access

    When an access already exists, devices can be removed from it by performing a `DELETE` operation on the `/accesses/{accessId}/devices` collection endpoint.

    The API Consumer provides the following information

    - a list of identifiers of the devices to be removed, using a device object as device identifier

    The API returns a confirmation of removal or, if not all devices could be removed, a result detailing which devices were removed and which failed.

    # Querying devices in an access

    All devices included in an access can be queried by performing a `GET` operation on the `/accesses/{accessId}/devices` endpoint. The query can be for a specific device or for devices with a specific status.

    # Querying one or more accesses

    All available accesses of the API consumer can be queried by performing a `GET` operation on the `/accesses` endpoint. The query can be filtered for accesses to a specific network or those including a specific device.

    A specific access of the API consumer can be queried by performing a `GET` operation on the `/accesses/{accessId}` endpoint, where the accessId has been obtained during the _create_ procedure.

    # Deleting an access

    A specific access of the API consumer can be deleted by performing a `DELETE` operation on the `/accesses/{accessId}` endpoint. Deletion of the access can be interpreted as removal of the permission for all the devices included in the access to access the network.

    <!-- CAMARA:MANDATORY:additional-error-responses:BEGIN -->

    # Additional CAMARA error responses

    The list of error codes in this API specification is not exhaustive. Therefore the API specification MAY not document some non-mandatory error statuses as indicated in `CAMARA API Design Guide`.

    Please refer to the `CAMARA_common.yaml` of the Commonalities Release associated to this API version for a complete list of error responses. The applicable Commonalities Release can be identified in the `API Readiness Checklist` document associated to this API version.

    As a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible error response if it is explicitly documented in the API.
    <!-- CAMARA:MANDATORY:additional-error-responses:END -->
    <!-- CAMARA:MANDATORY:request-body-strictness:BEGIN -->

    # Request body strictness

    This API rejects requests with JSON request bodies that contain properties not declared in this specification, at any nesting level. Unknown properties result in a `400 INVALID_ARGUMENT` response.
    <!-- CAMARA:MANDATORY:request-body-strictness:END -->

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: wip
  x-camara-commonalities: 0.8
externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/DedicatedNetworks
servers:
  - url: "{apiRoot}/dedicated-network-accesses/vwip"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root, defined by the service provider, e.g. `api.example.com` or `api.example.com/somepath`
tags:
  - name: Accesses
    description: Manage accesses to a dedicated network for devices
  - name: Devices
    description: Manage devices of an access to a dedicated network
paths:

  /accesses:
    get:
      tags:
        - Accesses
      summary: Get a list of accesses to dedicated networks, optionally filtered for a given device and/or for a given dedicated network
      description: |
        Get a list of accesses to dedicated networks, optionally filtered for a given device and/or for a given dedicated network
      operationId: listAccesses
      security:
        - openId:
            - dedicated-network-accesses:accesses:read
      parameters:
        - name: networkId
          in: query
          description: Dedicated network id
          schema:
            $ref: '#/components/schemas/NetworkId'
        - $ref: "#/components/parameters/x-device"
        - $ref: "../common/CAMARA_common.yaml#/components/parameters/x-correlator"
      responses:
        '200':
          description: List of existing accesses to dedicated networks, optionally filtered for a given device and/or for a dedicated network (the list can be empty)
          content:
            application/json:
              schema:
                type: array
                maxItems: 1000000
                items:
                  $ref: '#/components/schemas/AccessInfo'
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
    post:
      tags:
        - Accesses
      summary: Create an access to a dedicated network with given configuration, optionally including devices
      description: |
        Create an access to a dedicated network with given configuration, optionally including devices
        **NOTE:**
          - This API recommends usage of a two-legged access token, but if the invoker uses a three-legged token, the corresponding `device` identifier MUST be provided and must match the identifier in the access token.
      operationId: createAccess
      security:
        - openId:
            - dedicated-network-accesses:accesses:create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccessRequest'
      callbacks:
        notifications:
          "{$request.body#/sink}":
            post:
              tags:
                - Device access status callback
              summary: "Device access status notifications callback"
              description: |
                Important: this endpoint is to be implemented by the API consumer.
                It will be called upon change of the network access request status.
                Currently only DEVICE_STATUS_CHANGED event is defined.
              operationId: postNotification
              parameters:
                - $ref: "../common/CAMARA_common.yaml#/components/parameters/x-correlator"
              requestBody:
                required: true
                content:
                  application/cloudevents+json:
                    schema:
                      $ref: "#/components/schemas/AccessDeviceNotificationEvent"
                    examples:
                      DEVICE_STATUS_CHANGED_EXAMPLE:
                        $ref: "#/components/examples/DEVICE_STATUS_CHANGED_EXAMPLE"
              responses:
                "204":
                  description: Successful notification
                  headers:
                    x-correlator:
                      $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
                "400":
                  $ref: "#/components/responses/Generic400"
                "401":
                  $ref: "#/components/responses/Generic401"
                "403":
                  $ref: "#/components/responses/Generic403"
                "410":
                  $ref: "#/components/responses/Generic410"
              security:
                - {}
                - notificationsBearerAuth: []
      responses:
        '201':
          description: Successful creation of the access for all devices (if any)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccessSuccess'
          headers:
            Location:
              description: 'URL including the resource identifier of the newly created network access.'
              required: true
              schema:
                type: string
                maxLength: 2048
        '207':
          description: Successful creation of the access for some devices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccessPartialSuccess'
          headers:
            Location:
              description: 'URL including the resource identifier of the newly created network access.'
              required: true
              schema:
                type: string
                maxLength: 2048
        '400':
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "409":
          $ref: "#/components/responses/Generic409"
        "422":
          $ref: "#/components/responses/Generic422"

  /accesses/{accessId}:
    get:
      tags:
        - Accesses
      summary: Read access information
      description: |
        Read access information
      operationId: readAccess
      security:
        - openId:
            - dedicated-network-accesses:accesses:read
      parameters:
        - name: accessId
          description: access identifier
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/AccessId"
        - $ref: "../common/CAMARA_common.yaml#/components/parameters/x-correlator"
      responses:
        '200':
          description: Access information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessInfo'
        '400':
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"

    delete:
      tags:
        - Accesses
      summary: Delete an access
      description: |
        Delete an access
      operationId: deleteAccess
      security:
        - openId:
            - dedicated-network-accesses:accesses:delete
      parameters:
        - name: accessId
          description: access identifier
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/AccessId"
        - $ref: "../common/CAMARA_common.yaml#/components/parameters/x-correlator"
      responses:
        '204':
          description: Successful deletion of the access
        '400':
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"

  /accesses/{accessId}/devices:
    parameters:
      - name: accessId
        description: access identifier
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/AccessId"
      - $ref: "../common/CAMARA_common.yaml#/components/parameters/x-correlator"
    get:
      tags:
        - Devices
      summary: Read a paged list of devices with information included in the access, optionally filtered by device status
      description: |
        Read a paged list of devices with information included in the access, optionally filtered by device status
      operationId: listDevices
      security:
        - openId:
            - dedicated-network-accesses:devices:read
      parameters:
        - name: perPage
          in: query
          description: |
            Number of access devices to return per page
          schema:
            $ref: "../common/CAMARA_common.yaml#/components/schemas/PerPage"
        - name: page
          in: query
          description: |
            Number of the page of access devices to return
          schema:
            $ref: "../common/CAMARA_common.yaml#/components/schemas/Page"
        - name: deviceStatus
          in: query
          description: Only access devices with this status are to be returned
          schema:
            $ref: "#/components/schemas/DeviceStatus"
      responses:
        '200':
          description: A list of devices matching the given criteria and in the requested page (can be empty).
          headers:
            X-Total-Count:
              $ref: '../common/CAMARA_common.yaml#/components/headers/x-total-count'
            X-Total-Pages:
              $ref: '../common/CAMARA_common.yaml#/components/headers/x-total-pages'
            Link:
              $ref: '../common/CAMARA_common.yaml#/components/headers/link'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDevicesPage'
        '400':
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"

  /accesses/{accessId}/devices/add:
    parameters:
      - name: accessId
        description: access identifier
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/AccessId"
      - $ref: "../common/CAMARA_common.yaml#/components/parameters/x-correlator"
    post:
      tags:
        - Devices
      summary: Add devices to the access
      description: |
        Add devices to the access
      operationId: addDevicesToAccess
      security:
        - openId:
            - dedicated-network-accesses:devices:add
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddDevicesRequest"
      responses:
        '201':
          description: Successful addition of all the given devices
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddDevicesSuccess"
        '207':
          description: Partially successful addition of devices, success for at least one of the given devices
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddDevicesPartialSuccess"
        '400':
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "409":
          $ref: "#/components/responses/Generic409"
        "422":
          $ref: "#/components/responses/NoProcessableDevices422"

  /accesses/{accessId}/devices/remove:
    parameters:
      - name: accessId
        description: access identifier
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/AccessId"
      - $ref: "../common/CAMARA_common.yaml#/components/parameters/x-correlator"
    post:
      tags:
        - Devices
      summary: Remove devices from the access
      description: Remove devices from the access
      operationId: removeDevicesFromAccess
      security:
        - openId:
            - dedicated-network-accesses:devices:remove
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RemoveDevicesRequest"
      responses:
        '204':
          description: Successful removal of all the given devices
        '207':
          description: Partially successful removal of devices, success for at least one of the given devices
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RemoveDevicesPartialSuccess"
        '400':
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "409":
          $ref: "#/components/responses/Generic409"
        "422":
          $ref: "#/components/responses/NoProcessableDevices422"

components:
  securitySchemes:
    openId:
      description: OpenID Connect authentication
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
    notificationsBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: "{$request.body#/sinkCredential.credentialType}"
      description: |
        Bearer token for notification delivery. Token format is determined
        by `sinkCredential.credentialType` in the subscription request.

  parameters:
    x-device:
      name: x-device
      in: header
      description: Device object represented in a header
      schema:
        $ref: "#/components/schemas/SerializedDevice"

  schemas:
    AccessId:
      description: Network access id in UUID format
      type: string
      format: uuid
      maxLength: 36

    NetworkId:
      description: Network id in UUID format
      type: string
      format: uuid
      maxLength: 36

    DeviceStatus:
      description: |
        The current status of the device in the context of the access. The status can be one of the following:
        * `REQUESTED` - The device was requested to have access to the network. Possible transitions to GRANTED and DENIED states.
        * `GRANTED` - The device was granted access to the network by the CSP, and therefore the device can use the Dedicated Network when the network is in the ACTIVATED state. Possible transition to DENIED state.
        * `DENIED` - The device was denied access to the network by the CSP, and therefore the device can not use the Dedicated Network. The denial can be caused by a variety of conditions, such as lack of resources or system failure.

      type: string
      enum:
        - REQUESTED
        - GRANTED
        - DENIED

    ReasonInfo:
      description: |
        Information about the reason for a change
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          maxLength: 96
          description: A human-readable code to describe the reason
        message:
          type: string
          maxLength: 4096
          description: A human-readable description of what the reason represents

    DeviceStatusInfo:
      description: Additional information about the reason for the current device status
      type: object
      properties:
        reason:
          description: |
            Information about the reason for a device status change in the context of the access
          allOf:
            - $ref: "#/components/schemas/ReasonInfo"
            - type: object
              properties:
                code:
                  enum:
                    - REQUEST_APPROVED
                    - REQUEST_REJECTED
                    - REQUEST_FAILED
                    - ACCESS_REVOKED
                    - ACCESS_FAILED

    AccessDevicesPage:
      description: A page of access devices
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          $ref: "#/components/schemas/AccessDevices"
        pagination:
          $ref: "../common/CAMARA_common.yaml#/components/schemas/Pagination"

    AccessDevices:
      description: A list of access devices
      type: array
      minItems: 0
      maxItems: 9007199254740991
      items:
        $ref: "#/components/schemas/AccessDevice"

    AccessDevice:
      description: Information about a single device included in an access
      type: object
      properties:
        device:
          $ref: "../common/CAMARA_common.yaml#/components/schemas/Device"
        status:
          $ref: "#/components/schemas/DeviceStatus"
        statusInfo:
          $ref: "#/components/schemas/DeviceStatusInfo"
      required:
        - device
        - status

    BaseAccessInfo:
      description: Common attributes of an access to a dedicated network
      type: object
      properties:
        networkId:
          $ref: "#/components/schemas/NetworkId"
        qosProfiles:
          description: (Optional) List of supported QOS profiles usable for the device(s). When absent, all QosProfiles of the network are supported. Only a subset of the QOS profiles of the network is allowed
          type: array
          minItems: 1
          maxItems: 32
          items:
            $ref: "#/components/schemas/QosProfileName"
        defaultQosProfile:
          $ref: "#/components/schemas/QosProfileName"
        sink:
          description: The address to which events shall be delivered using the selected protocol.
          type: string
          format: uri
          pattern: ^https:\/\/.+$
          maxLength: 2048
        sinkCredential:
          $ref: '../common/CAMARA_event_common.yaml#/components/schemas/SinkCredential'
      required:
        - networkId

    CreateAccessRequest:
      description: Attributes required to create a dedicated network access for devices
      allOf:
        - $ref: "#/components/schemas/BaseAccessInfo"
        - type: object
          properties:
            devices:
              allOf:
                - $ref: "#/components/schemas/Devices"
                - minItems: 1
                - maxItems: 100

    CreateAccessSuccess:
      description: |
        Response body used when access was created successfully for all devices (if any)
      allOf:
        - $ref: '#/components/schemas/AccessInfo'

    CreateAccessPartialSuccess:
      description: |
        Response body used when access was created successfully but for some devices only.
        Successful devices are returned in `recentAccessDevices` while failed devices are listed in `results`.
        **NOTE:** Only failed devices are listed in `results`.
      allOf:
        - $ref: '#/components/schemas/AccessInfo'
        - $ref: '#/components/schemas/ResultsForDevices'

    AccessStats:
      description: Statistical information for a dedicated network access
      type: object
      properties:
        totalDevices:
          description: the total number of devices included in the access (regardless of status)
          type: integer
          format: int64
          minimum: 0
          maximum: 9007199254740991
        totalGranted:
          description: the total number of devices included in the access with status GRANTED
          type: integer
          format: int64
          minimum: 0
          maximum: 9007199254740991
        totalDenied:
          description: the total number of devices included in the access with status DENIED
          type: integer
          format: int64
          minimum: 0
          maximum: 9007199254740991
      required:
        - totalDevices
        - totalGranted
        - totalDenied

    AccessInfo:
      description: |
       Information about a dedicated network access, which includes the following:
       * id - a unique identifier of the access
       * stats - access statistics
       * recentAccessDevices - a list of recently handled devices with information (can be empty)
        **NOTE:** recentAccessDevices is limited to a maximum of 100 devices and may therefore not be a complete list
      allOf:
        - $ref: "#/components/schemas/BaseAccessInfo"
        - type: object
          properties:
            id:
              $ref: "#/components/schemas/AccessId"
            stats:
              $ref: "#/components/schemas/AccessStats"
            recentAccessDevices:
              allOf:
                - $ref: "#/components/schemas/AccessDevices"
                - minItems: 1
                - maxItems: 100
          required:
            - id
            - stats

    AddDevicesRequest:
      description: Request body used to add devices to an access
      allOf:
        - $ref: "#/components/schemas/Devices"
        - minItems: 1
        - maxItems: 100

    AddDevicesSuccess:
      description: |
        Response body used when all devices could be added to an access successfully.
        It contains a list of `AccessDevice`s, one per device.
      allOf:
        - $ref: '#/components/schemas/AccessDevices'
        - minItems: 1
        - maxItems: 100

    AddDevicesPartialSuccess:
      description: |
        Response body used when not all devices could be added successfully.
        It contains a list of results, one result per device, detailing the result of the attempt to add the device to the access.
        **NOTE:** Both successful and failed devices are listed in `results`. A successful result for a device contains a `deviceAccess`.
      allOf:
        - $ref: "#/components/schemas/ResultsForDevices"

    RemoveDevicesRequest:
      description: Request body used to remove devices from an access
      allOf:
        - $ref: "#/components/schemas/Devices"
        - minItems: 1
        - maxItems: 100

    RemoveDevicesPartialSuccess:
      description: |
        Response body used when not all devices could be removed successfully.
        It contains a list of results, one result per failed device, detailing the result of the failed attempt to remove the device from the access.
        **NOTE:** Only failed devices are listed in `results`.
      allOf:
        - $ref: "#/components/schemas/ResultsForDevices"

    ErrorResults:
      description: |
        Response body used when none of the devices could be processed successfully.
        It contains the overall error information and a list of results, one result per device.
      allOf:
        - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
        - $ref: "#/components/schemas/ResultsForDevices"

    ResultsForDevices:
      description: An object describing results of an operation targetting mutlpiple devices
      type: object
      properties:
        results:
          description: A list of operation results, one result per device
          type: array
          items:
            $ref: '#/components/schemas/ResultForDevice'
          minItems: 1
          maxItems: 100

    ResultForDevice:
      description: Information about the result of an operation for a device
      type: object
      required:
        - device
        - status
        - message
      properties:
        device:
          $ref: "../common/CAMARA_common.yaml#/components/schemas/Device"
        status:
          type: integer
          format: int32
          minimum: 100
          maximum: 599
          description: The HTTP status code for this specific device operation (e.g., 201, 404, 409)
          example: 201
        code:
          type: string
          maxLength: 96
          description: A human-readable code to describe the result
        message:
          type: string
          maxLength: 4096
          description: A human-readable description of what the result represents
        accessDevice:
          $ref: '#/components/schemas/AccessDevice'

    AccessDeviceEventType:
      description: Enum of event types for the Dedicated Network Accesses API.
      type: string
      enum:
        - org.camaraproject.dedicated-network-accesses.v0.device-status-changed

    AccessDeviceNotificationEvent:
      description: Notification event for device access status changes. Constrains the CloudEvent `type` to access-specific event types.
      allOf:
        - $ref: "../common/CAMARA_event_common.yaml#/components/schemas/CloudEvent"
        - type: object
          properties:
            type:
              $ref: "#/components/schemas/AccessDeviceEventType"
      discriminator:
        propertyName: 'type'
        mapping:
          org.camaraproject.dedicated-network-accesses.v0.device-status-changed: "#/components/schemas/EventDeviceStatusChanged"

    EventDeviceStatusChanged:
      description: Event to notify a status change of one or more devices in the context of an access to a dedicated network
      allOf:
        - $ref: "#/components/schemas/AccessDeviceNotificationEvent"
        - type: object
          properties:
            data:
              type: object
              description: Status change details for one or more devices in the context of an access to a dedicated network
              required:
                - accessId
                - accessDevices
              properties:
                accessId:
                  $ref: "#/components/schemas/AccessId"
                accessDevices:
                  type: array
                  items:
                    $ref: "#/components/schemas/AccessDevice"
                  minItems: 1
                  maxItems: 100
          required:
            - data

    Devices:
      description: A list of devices
      type: array
      maxItems: 9007199254740991
      items:
        $ref: "../common/CAMARA_common.yaml#/components/schemas/Device"

    SerializedDevice:
      description: |
        Device object serialized to a string for use as a device identifier.
        It is serialized according to RFC 8941 as a structured field value where
        the Device object is a dictionary, with the following additonal provisions
          - property names are changed to lower case to comply with the RFC and are ordered alphabetically
          - serializing property values must comply with the RFC depending on the type, and in particular
            - if the property value is a string which contains only ASCII characters, the string can be serialized as String,
              as per section 3.3.3 of the RFC
            - if the property value is a string and contains non-ASCII characters, the string must be serialized as Byte Sequence using UTF-8 encoding,
              as per section 3.3.5 of the RFC
      type: string
      maxLength: 4096
      example: 'phonenumber="+123456789"'

    QosProfileName:
      description: |
        A unique name for identifying a specific QoS profile.
        This may follow different formats depending on the service providers implementation.
        Some options addresses:
          - A UUID style string
          - Support for predefined profiles QOS_S, QOS_M, QOS_L, and QOS_E
          - A searchable descriptive name
        The set of QoS Profiles that an operator is offering can be retrieved by means of the QoS Profile API.
      type: string
      example: QCI_1_voice
      minLength: 3
      maxLength: 256
      pattern: "^[a-zA-Z0-9_.-]+$"

  responses:
    Generic400:
      description: Bad Request
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 400
                  code:
                    enum:
                      - INVALID_ARGUMENT
                      - OUT_OF_RANGE
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
            GENERIC_400_OUT_OF_RANGE:
              description: Out of Range. Specific Syntax Exception used when a given field has a pre-defined range or a invalid filter criteria combination is requested
              value:
                status: 400
                code: OUT_OF_RANGE
                message: Client specified an invalid range.

    Generic401:
      description: Unauthorized
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 401
                  code:
                    enum:
                      - UNAUTHENTICATED
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated and a new authentication is required
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials. A new authentication is required.

    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 403
                  code:
                    enum:
                      - PERMISSION_DENIED
                      - INVALID_TOKEN_CONTEXT
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
            GENERIC_403_INVALID_TOKEN_CONTEXT:
              description: Reflect some inconsistency between information in some field of the API and the related OAuth2 Token
              value:
                status: 403
                code: INVALID_TOKEN_CONTEXT
                message: "{{field}} is not consistent with access token."

    Generic404:
      description: Not found
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 404
                  code:
                    enum:
                      - NOT_FOUND
                      - IDENTIFIER_NOT_FOUND
          examples:
            GENERIC_404_NOT_FOUND:
              description: Resource is not found
              value:
                status: 404
                code: NOT_FOUND
                message: The specified resource is not found.
            GENERIC_404_IDENTIFIER_NOT_FOUND:
              description: Some identifier cannot be matched to a device
              value:
                status: 404
                code: IDENTIFIER_NOT_FOUND
                message: Device identifier not found.

    Generic409:
      description: Conflict
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 409
                  code:
                    enum:
                      - ABORTED
                      - ALREADY_EXISTS
                      - CONFLICT
                      - INCOMPATIBLE_STATE
          examples:
            GENERIC_409_ABORTED:
              description: Concurrency of processes of the same nature/scope
              value:
                status: 409
                code: ABORTED
                message: Concurrency conflict.
            GENERIC_409_ALREADY_EXISTS:
              description: Trying to create an existing resource
              value:
                status: 409
                code: ALREADY_EXISTS
                message: The resource that a client tried to create already exists.
            GENERIC_409_CONFLICT:
              description: Duplication of an existing resource
              value:
                status: 409
                code: CONFLICT
                message: A specified resource duplicate entry found.
            GENERIC_409_INCOMPATIBLE_STATE:
              description: A resource referenced in the request is in an incompatible state for the requested operation
              value:
                status: 409
                code: INCOMPATIBLE_STATE
                message: A referenced resource is in an incompatible state.

    Generic410:
      description: Gone
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 410
                  code:
                    enum:
                      - GONE
          examples:
            GENERIC_410_GONE:
              description: Use in notifications flow to allow API Consumer to indicate that its callback is no longer available
              value:
                status: 410
                code: GONE
                message: Access to the target resource is no longer available.

    Generic422:
      description: Unprocessable Content
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 422
                  code:
                    enum:
                      - SERVICE_NOT_APPLICABLE
                      - MISSING_IDENTIFIER
                      - UNSUPPORTED_IDENTIFIER
                      - UNNECESSARY_IDENTIFIER
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service not applicable for the provided identifier
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not available for the provided identifier.
            GENERIC_422_MISSING_IDENTIFIER:
              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: The device cannot be identified.
            GENERIC_422_UNSUPPORTED_IDENTIFIER:
              description: None of the provided identifiers is supported by the implementation
              value:
                status: 422
                code: UNSUPPORTED_IDENTIFIER
                message: The identifier provided is not supported.
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              description: An explicit identifier is provided when a device or phone number has already been identified from the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: The device is already identified by the access token.

    NoProcessableDevices422:
      description: Unprocessable Content due to that none of the requested devices could be processed successfully
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorResults"
              - type: object
                properties:
                  status:
                    enum:
                      - 422
                  code:
                    enum:
                      - DEDICATED_NETWORK_ACCESS.NO_VALID_DEVICE
          examples:
            DEDICATED_NETWORK_ACCESS_422_NO_VALID_DEVICE:
              description: The request is syntacticaly correct but none of the devices given in the request could be processed successfully.
              value:
                status: 422
                code: DEDICATED_NETWORK_ACCESS.NO_VALID_DEVICE
                message: None of the devices in the request could be processed successfully.
                results:
                  - device:
                      phoneNumber: "+49123456789"
                    status: 404
                    code: IDENTIFIER_NOT_FOUND
                    message: Device identifier not found.
                  - device:
                      phoneNumber: "+491234500001"
                    status: 409
                    code: CONFLICT
                    message: Client specified a duplicate device identifier.
  examples:

    DEVICE_STATUS_CHANGED_EXAMPLE:
      summary: Device is GRANTED access to a dedicated network
      description: Cloud event example when a device's status in the context of an access to a dedicated network changes to GRANTED
      value:
        id: 625b2d4b-4da7-4f07-9169-e60ffdf7667c
        source: 'https://api.example.com/dedicated-network-accesses/v0/accesses/b69e5404-3871-448d-8f9f-11dc5d29a4c8'
        specversion: '1.0'
        type: "org.camaraproject.dedicated-network-accesses.v0.device-status-changed"
        time: '2024-11-29T13:04:00Z'
        data:
          accessId: b69e5404-3871-448d-8f9f-11dc5d29a4c8
          accessDevices:
            - device:
                phoneNumber: "+49123456789"
              status: GRANTED
              statusInfo:
                code: REQUEST_APPROVED
                message: The request to grant the device access to the network was approved.
